### PR TITLE
this commit will introduce context for logged in user and allow posti…

### PR DESCRIPTION
**Pull request by harrycs1**
…ng of a new comment to an article

### CODE REVIEW

**Review by popatre — CHANGES_REQUESTED** [review]
- nice posting functionality to the api
- Nice posting at the logged in user

- [x] We need at least some basic validation on the inputs, at least to stop blank posts - i can spam empty posts at the moment
- [x] Please reset the form after posting
- [x] Need to disable the form when posting to stop duplicates or some loading pattern to stop someone spamming the post button on a slow connection, or blank posts
- [ ] Need to handle the errors when a post fails. The post remains on the screen despite the post failing in the backend at the moment. I dont seem to get any message, just the failed posted which then disappears after refreshing.

**Review by popatre — CHANGES_REQUESTED** [review]
The offline posting still has no feedback to say anything has gone wrong

https://jam.dev/c/3dc3f6f7-b6d4-4409-a55e-fd388b5db72a

**Review by popatre — CHANGES_REQUESTED** [review]
Its a little better, however,

- [x] The comment still appears on the page, despite the message saying something went wrong. Its confusing UX/conflicting messages

**Review by popatre — CHANGES_REQUESTED** [review]
its one thing, but a very small thing

- [ ] If i delete whilst offline, the error message appear saying to try again 👍 If i then go online and try again, the error message remains. I'd reset the error message in your .then so that it doesnt remain forever.

**Review by nc-modou — APPROVED** [review]
Great response to Jonathan's feedback. The offline message clears appropriately now, happy to see this one merged 👍

**Pull request merged**
